'use client';
import {useEffect,useMemo,useState} from 'react';
import {onAuthStateChanged,signInWithPopup,signOut} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,getDocs,limit,onSnapshot,orderBy,query,serverTimestamp,setDoc,where} from 'firebase/firestore';
import {auth,db,googleProvider,configured} from '../lib/firebase';
import {APP_CONFIG} from '../config/app.config';

type Role='owner'|'manager'|'employee'|'watchman';
type Lang='en'|'mr';
type Worker={id:string;name:string;code:string;email:string;payment:'hour'|'kg'|'task';rate:number;active:boolean};
const OWNER=APP_CONFIG.bootstrapOwnerEmail;
const labels={en:{dash:'Dashboard',stock:'Stock',inward:'Goods Inward',batches:'Batches',workers:'Workers',attendance:'Attendance',payroll:'Payroll',reports:'Reports',logbook:'Logbook',settings:'Settings',login:'Continue with Google',welcome:'Factory Overview',receive:'Receive Goods',newBatch:'New Batch',checkIn:'Check In',checkOut:'Check Out',break:'Break',save:'Save',today:'Today',total:'Total Stock',received:'Received Today',production:'Production Today',present:'Workers Present',active:'Active Batches',owner:'Owner',manager:'Manager',employee:'Worker',watchman:'Watchman',english:'English',marathi:'मराठी',dark:'Dark',light:'Light',restricted:'This Google account has not been assigned access.',email:'Owner email'},mr:{dash:'डॅशबोर्ड',stock:'साठा',inward:'माल आवक',batches:'बॅच',workers:'कामगार',attendance:'हजेरी',payroll:'पगार',reports:'अहवाल',logbook:'लॉगबुक',settings:'सेटिंग',login:'Google ने प्रवेश करा',welcome:'फॅक्टरीचा आढावा',receive:'माल नोंदवा',newBatch:'नवी बॅच',checkIn:'आत घ्या',checkOut:'बाहेर करा',break:'विश्रांती',save:'जतन करा',today:'आज',total:'एकूण साठा',received:'आजची आवक',production:'आजचे उत्पादन',present:'उपस्थित कामगार',active:'चालू बॅच',owner:'मालक',manager:'मॅनेजर',employee:'कामगार',watchman:'वॉचमन',english:'English',marathi:'मराठी',dark:'डार्क',light:'लाइट',restricted:'या Google खात्याला अजून प्रवेश दिलेला नाही.',email:'मालकाचा ईमेल'}} as const;
const nav=[['dash','🏠'],['stock','📦'],['inward','⬇️'],['batches','🧵'],['workers','👷'],['attendance','🟢'],['payroll','💰'],['reports','📊'],['logbook','📒'],['settings','⚙️']] as const;
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date())}
async function audit(actor:any,action:string,entity:string,summary:string){if(db&&actor)await addDoc(collection(db,'audit_logs'),{actorUid:actor.uid,actorEmail:actor.email||'',actorName:actor.displayName||actor.email||'',action,entity,summary,createdAt:serverTimestamp()})}

export default function Home(){
 const [user,setUser]=useState<any>(null),[role,setRole]=useState<Role|null>(null),[lang,setLang]=useState<Lang>('mr'),[dark,setDark]=useState(false),[tab,setTab]=useState('dash'),[workers,setWorkers]=useState<Worker[]>([]),[logs,setLogs]=useState<any[]>([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true);
 const t=labels[lang];
 useEffect(()=>{const l=localStorage.getItem('gaddam-lang') as Lang;if(l)setLang(l);const d=localStorage.getItem('gaddam-dark');if(d)setDark(d==='1');if(!auth){setLoading(false);return}return onAuthStateChanged(auth,async u=>{setUser(u);if(!u){setRole(null);setLoading(false);return}const email=(u.email||'').toLowerCase();if(email===OWNER){setRole('owner');setLoading(false);return}try{const s=await getDoc(doc(db!,'access_emails',email));setRole(s.exists()&&s.data().active!==false?s.data().role:null);if(!s.exists())setMsg(t.restricted)}catch(e){setMsg('Firebase access check failed')}setLoading(false)})},[t.restricted]);
 useEffect(()=>{localStorage.setItem('gaddam-lang',lang);localStorage.setItem('gaddam-dark',dark?'1':'0');document.documentElement.dataset.theme=dark?'dark':'light'},[lang,dark]);
 useEffect(()=>{if(!db||!user)return;const q=query(collection(db,'workers'),orderBy('name'));return onSnapshot(q,s=>setWorkers(s.docs.map(d=>({id:d.id,...d.data()} as Worker))),()=>{});},[user]);
 useEffect(()=>{if(!db||role!=='owner')return;const q=query(collection(db,'audit_logs'),orderBy('createdAt','desc'),limit(30));return onSnapshot(q,s=>setLogs(s.docs.map(d=>({id:d.id,...d.data()}))),()=>{});},[role]);
 const login=async()=>{setMsg('');if(!auth||!configured){setMsg('Firebase environment variables are not configured in Vercel.');return}try{await signInWithPopup(auth,googleProvider)}catch(e:any){setMsg(e?.message||'Google sign-in failed')}};
 if(loading)return <main className="center"><div className="card loginbox"><div className="logo">GF</div><h2>Gaddam Factory</h2><p>Loading…</p></div></main>;
 if(!user||!role)return <Login t={t} lang={lang} setLang={setLang} login={login} msg={msg} configured={configured}/>;
 const title=tab==='dash'?t.dash:({stock:t.stock,inward:t.inward,batches:t.batches,workers:t.workers,attendance:t.attendance,payroll:t.payroll,reports:t.reports,logbook:t.logbook,settings:t.settings} as any)[tab];
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="logo">GF</div><div><b>Gaddam Factory</b><small>Textile Operations</small></div></div><div className="role">● {({owner:t.owner,manager:t.manager,employee:t.employee,watchman:t.watchman} as any)[role]}</div><nav>{nav.filter(([id])=>id!=='settings'||role==='owner').map(([id,ico])=><button className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)} key={id}>{ico}<span>{(t as any)[id]}</span></button>)}</nav><div className="bottom"><button className="nav" onClick={()=>setLang(lang==='mr'?'en':'mr')}>🌐 <span>{lang==='mr'?t.english:t.marathi}</span></button><button className="nav" onClick={()=>setDark(!dark)}>{dark?'☀️':'🌙'} <span>{dark?t.light:t.dark}</span></button><button className="nav danger" onClick={()=>auth&&signOut(auth)}>↪️ <span>Sign out</span></button></div></aside><header className="mobilebar"><b>Gaddam Factory</b><button onClick={()=>setDark(!dark)}>{dark?'☀️':'🌙'}</button></header><main className="main"><header className="top"><div><small>{t[role]}</small><h1>{title}</h1></div><div className="user"><b>{user.displayName||user.email}</b><span>{user.email}</span></div></header>{tab==='dash'&&<Dashboard t={t} setTab={setTab}/>} {tab==='stock'&&<Stock/>}{tab==='inward'&&<Inward user={user}/>} {tab==='batches'&&<Batches user={user}/>} {tab==='workers'&&<Workers role={role} user={user} workers={workers}/>} {tab==='attendance'&&<Attendance user={user} workers={workers}/>} {tab==='payroll'&&<Payroll workers={workers}/>} {tab==='reports'&&<Reports/>}{tab==='logbook'&&<Logbook logs={logs}/>} {tab==='settings'&&role==='owner'&&<Settings user={user}/>}</main></div>
}
function Login({t,lang,setLang,login,msg,configured}:any){return <main className="center"><div className="card loginbox"><div className="logo big">GF</div><div className="eyebrow">TEXTILE FACTORY</div><h1>{t.loginTitle||'Gaddam Factory'}</h1><p>{lang==='mr'?'फॅक्टरी व्यवस्थापन प्रणाली':'Factory management system'}</p><button className="google" onClick={login}><b>G</b>{t.login}</button>{msg&&<div className="alert">⚠️ {msg}</div>}<div className="langs"><button className={lang==='mr'?'sel':''} onClick={()=>setLang('mr')}>मराठी</button><button className={lang==='en'?'sel':''} onClick={()=>setLang('en')}>English</button></div><small>Owner: {OWNER}</small>{!configured&&<div className="demo">Firebase config missing — sign-in is disabled.</div>}</div></main>}
function Dashboard({t,setTab}:any){const cards=[["📦",t.total,'15,820 kg'],['⬇️',t.received,'2,450 kg'],['⚙️',t.production,'1,820 kg'],['👷',t.present,'127 / 145'],['🧵',t.active,'12']];return <><div className="welcome"><div><span>{t.today}</span><h2>{t.welcome}</h2><p>Real-time factory operations at a glance.</p></div><button onClick={()=>setTab('inward')}>⬇️ {t.receive}</button></div><div className="metrics">{cards.map(c=><section className="card metric" key={c[1]}><span>{c[0]} {c[1]}</span><strong>{c[2]}</strong></section>)}</div><div className="quick"><button onClick={()=>setTab('inward')}>🟢 {t.receive}</button><button onClick={()=>setTab('batches')}>🔵 {t.newBatch}</button><button onClick={()=>setTab('workers')}>🟡 {t.workers}</button><button onClick={()=>setTab('attendance')}>🔴 {t.attendance}</button></div><section className="card"><h3>Factory workflow</h3><div className="steps"><span>1. Goods Inward</span><b>→</b><span>2. Stock</span><b>→</b><span>3. Batch</span><b>→</b><span>4. Production</span><b>→</b><span>5. Payroll</span></div></section></>}
function Stock(){return <section className="card"><h2>📦 Stock</h2>{[['Cotton','10 Single','4,500 kg'],['Cotton','20 Single','3,200 kg'],['Polyester','20 Single','2,100 kg'],['Cotton','30 Single','1,860 kg']].map(x=><div className="row" key={x[0]+x[1]}><div><b>{x[0]} · {x[1]}</b><small>Available stock</small></div><strong>{x[2]}</strong><span className="pill">Available</span></div>)}</section>}
function Inward({user}:any){const [yarn,setYarn]=useState('Cotton · 10 Single'),[pote,setPote]=useState(20),[weight,setWeight]=useState(50),[boxes,setBoxes]=useState(0),[supplier,setSupplier]=useState(''),[saving,setSaving]=useState(false),[file,setFile]=useState<File|null>(null);const total=pote*weight+boxes*weight;const save=async()=>{if(!db)return;setSaving(true);try{await addDoc(collection(db,'goods_receipts'),{supplier,yarnType:yarn,poteCount:Number(pote),boxCount:Number(boxes),unitWeightKg:Number(weight),totalKg:total,gatePassFileName:file?.name||'',receivedDate:dateKey(),createdBy:user.uid,createdAt:serverTimestamp()});await audit(user,'CREATE','goods_receipt',`Received ${total} kg ${yarn}`);alert('Goods inward saved')}catch(e:any){alert(e.message)}finally{setSaving(false)}};return <div className="grid2"><section className="card form"><h2>⬇️ Receive Goods</h2><label>Supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier name"/></label><label>Yarn Type<select value={yarn} onChange={e=>setYarn(e.target.value)}><option>Cotton · 10 Single</option><option>Cotton · 20 Single</option><option>Polyester · 20 Single</option></select></label><div className="tw"><label>Pote / Bori<input type="number" min="0" value={pote} onChange={e=>setPote(+e.target.value)}/></label><label>Boxes<input type="number" min="0" value={boxes} onChange={e=>setBoxes(+e.target.value)}/></label></div><label>Package weight<select value={weight} onChange={e=>setWeight(+e.target.value)}><option value="50">50 kg</option><option value="60">60 kg</option></select></label><div className="total"><span>Total weight</span><b>{total.toLocaleString()} kg</b></div><label className="upload">📷 Gate Pass / Delivery Note<input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?.name||'Take photo or choose image'}</small></label><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':'💾 Save Goods Receipt'}</button></section><section className="card"><h3>Receipt rules</h3><p>• Pote/Bori and Box are tracked separately.</p><p>• Default package weights: 50 kg and 60 kg.</p><p>• Every receipt creates a stock movement and audit entry.</p><p>• Gate Pass / Delivery Note can be captured from the phone camera.</p></section></div>}
function Batches({user}:any){const [yarn,setYarn]=useState('Cotton · 10 Single'),[kg,setKg]=useState(500),[note,setNote]=useState(''),[saving,setSaving]=useState(false);const save=async()=>{if(!db)return;setSaving(true);try{await addDoc(collection(db,'batches'),{yarnType:yarn,inputKg:Number(kg),note,status:'created',createdBy:user.uid,createdAt:serverTimestamp()});await audit(user,'CREATE','batch',`Batch ${yarn}, ${kg} kg`);alert('Batch created')}catch(e:any){alert(e.message)}finally{setSaving(false)}};return <section className="card form narrow"><h2>🧵 New Batch</h2><label>Yarn Type<select value={yarn} onChange={e=>setYarn(e.target.value)}><option>Cotton · 10 Single</option><option>Cotton · 20 Single</option><option>Polyester · 20 Single</option></select></label><label>Input KG<input type="number" value={kg} onChange={e=>setKg(+e.target.value)}/></label><label>Notes<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional notes"/></label><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':'➕ Create Batch'}</button></section>}
function Workers({role,user,workers}:any){const [name,setName]=useState(''),[email,setEmail]=useState(''),[payment,setPayment]=useState<'hour'|'kg'|'task'>('kg'),[rate,setRate]=useState(4);const add=async()=>{if(!db||!name)return;const ref=await addDoc(collection(db,'workers'),{name,code:`W-${Date.now().toString().slice(-5)}`,email,payment,rate:Number(rate),active:true,createdAt:serverTimestamp()});if(email)await setDoc(doc(db,'access_emails',email.toLowerCase()),{email:email.toLowerCase(),role:'employee',active:true,workerId:ref.id,updatedAt:serverTimestamp()});await audit(user,'CREATE','worker',`Added worker ${name}`);setName('');setEmail('')};return <div className="grid2"><section className="card"><h2>👷 Workers</h2>{workers.length===0?<p>No workers yet.</p>:workers.map((w:Worker)=><div className="row" key={w.id}><div><b>{w.name}</b><small>{w.code} · {w.payment} · ₹{w.rate}</small></div><span className="pill">{w.active?'Active':'Inactive'}</span></div>)}</section>{(role==='owner'||role==='manager')&&<section className="card form"><h2>➕ Add Worker</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Google login email"/></label><label>Payment basis<select value={payment} onChange={e=>setPayment(e.target.value as any)}><option value="hour">Per Hour</option><option value="kg">Per KG</option><option value="task">Per Task</option></select></label><label>Rate<input type="number" value={rate} onChange={e=>setRate(+e.target.value)}/></label><button className="primary" onClick={add}>Save Worker</button></section>}</div>}
function Attendance({user,workers}:any){const act=async(w:Worker,type:string)=>{if(!db)return;await addDoc(collection(db,'attendance'),{workerId:w.id,workerUid:'',workerName:w.name,date:dateKey(),action:type,at:serverTimestamp()});await audit(user,type,'attendance',`${w.name} ${type}`)};return <section className="card"><div className="sectionhead"><h2>🟢 Attendance</h2><span>{dateKey()}</span></div>{workers.map((w:Worker)=><div className="row" key={w.id}><div><b>👷 {w.name}</b><small>{w.code}</small></div><div className="actions"><button className="green" onClick={()=>act(w,'check_in')}>🟢 Check In</button><button className="yellow" onClick={()=>act(w,'break')}>🟡 Break</button><button className="red" onClick={()=>act(w,'check_out')}>🔴 Check Out</button></div></div>)}</section>}
function Payroll({workers}:any){return <section className="card"><h2>💰 Payroll</h2><p>Manager review → Owner approval → Paid</p>{workers.map((w:Worker)=><div className="row" key={w.id}><div><b>{w.name}</b><small>{w.payment} · ₹{w.rate}</small></div><span>Pending</span></div>)}</section>}
function Reports(){return <div className="metrics"><section className="card"><h3>📦 Stock Report</h3><p>Opening, inward, reserved, consumed and closing stock.</p></section><section className="card"><h3>🧵 Production</h3><p>Batch-wise input, worker output and accepted KG.</p></section><section className="card"><h3>💰 Payroll</h3><p>Attendance, KG and task earnings by period.</p></section></div>}
function Logbook({logs}:any){return <section className="card"><div className="sectionhead"><h2>📒 Owner Logbook</h2><span>Latest 30</span></div>{logs.length===0?<p>No audit entries yet.</p>:logs.map((x:any)=><div className="row" key={x.id}><div><b>{x.action} · {x.entity}</b><small>{x.summary} · {x.actorEmail}</small></div><span>{x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('en-IN'):''}</span></div>)}</section>}
function Settings({user}:any){const [email,setEmail]=useState('');const add=async()=>{if(!db||!email)return;await setDoc(doc(db,'access_emails',email.toLowerCase()),{email:email.toLowerCase(),role:'owner',active:true,createdAt:serverTimestamp()});await audit(user,'CREATE','access_email',`Added owner ${email}`);setEmail('');alert('Owner added')};return <div className="grid2"><section className="card form"><h2>⚙️ Owner Access</h2><p>Add father/brothers/other owners by their Google account email.</p><label>Owner email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@gmail.com"/></label><button className="primary" onClick={add}>Add Owner</button></section><section className="card"><h3>Factory configuration</h3><p>Company: Gaddam Factory</p><p>Timezone: Asia/Kolkata</p><p>Default Pote/Bori: 50 kg, 60 kg</p><p>Payment: hourly / KG / task</p><p>Languages: Marathi / English</p></section></div>}
